config/routes.rb
Rails.application.routes.draw do

  get 'emails/new'
  get 'emails/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  ActiveAdmin.routes(self)

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :admin_users, ActiveAdmin::Devise.config

    root 'relatives#index'

    get '/collaborators/new',      to: 'users#add_collaborator'
    get '/collaborators',      to: 'users#collaborators'

    resources :categories
    resources :authentications, only: [:destroy]
    resources :relationships,  only: [:create, :destroy]
    resources :emails,  only: :create
    resources :pages, only: :show
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :relatives do
      resources :categories
    end
  end
end

app/models/relative.rb
class Relative < ApplicationRecord
  belongs_to :user

  has_many :category_relatives, dependent: :nullify
  has_many :categories, through: :category_relatives

  validates :first_name, presence: true, length:  { minimum: 3, maximum: 20 }
  validates :second_name, presence: true, length:  { minimum: 3 , maximum: 40}
  validates :born, presence: true, length:  { minimum: 9, maximum: 20 }
  validates :description, presence: true, length:  {  minimum: 20 }

  mount_uploaders :images, ImageUploader

  paginates_per 12

  def to_param
    "#{id}-#{first_name.parameterize}-#{second_name.parameterize}"
  end
end

app/controllers/relatives_controller.rb
class RelativesController < ApplicationController
  before_action :find_relative, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:destroy, :edit, :update]
  # caches_action :index

  def index
    @categories = Category.all
    @user = current_user
    @relatives = @user.relatives.order(created_at: :desc).page(params[:page]) if @user.present?
    @relatives = @relatives.where(id: CategoryRelative.where(category_id: params[:filter]).pluck(:relative_id)).page(params[:page]) if params[:filter].present?
    # @relatives = Relative.search(params[:search]).order(created_at: :asc).page(params[:page]) if params[:search]
    #
    # respond_to do |format|
    #   format.html
    #   # format.js
    #   format.json { render json: @relatives.pluck(:first_name) } if @relatives.present?
    # end
  end

  def new
    @relative = Relative.new
    @user = current_user
  end

  def create
    @relative = current_user.relatives.build(relative_params)
    @user = current_user
    if @relative.save
      redirect_to root_url
      flash[:success] = t('.save')
    else
      render 'new'
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    if @relative.update_attributes(relative_params)
      flash[:success] = t('.edit')
      redirect_to @relative
    else
      redirect_to 'edit'
    end
  end

  def destroy
    @relative.destroy
    flash[:success] = t('.remove')
    redirect_to root_url
  end

private

  def relative_params
    params.require(:relative).permit(:first_name, :second_name, :maiden_name, :description, :published, :born, :family_status, :children, {images: []}, {category_ids: []})
  end

  def find_relative
    @relative = Relative.find(params[:id])
  end

  def find_user
    @user = User.find(params[:id])
  end

  def correct_user
    @relative = current_user.relatives.find_by(id: params[:id])
    redirect_to root_url if @relative.nil?
  end
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/views/relatives/_categories.html.erb
<div>
  <%= form_tag relatives_path, method: :get do %>
  <ul class="category">
        <% @user.categories.each do |category| %>
        <li>
          <%= check_box_tag "filter[]", category.id, params[:filter] ? params[:filter].include?(category.id.to_s) : false, id: "cb#{category.id}", remote: true %>

          <label for="cb<%= category.id %>"><%= category.name %></label>

          <b class=''>(<%= category.relatives.count %>)</b>
        </li>
        <% end %>
      </ul>
      <%= submit_tag t('.find'), class: 'btn btn-success btn_category btn-sm' if @categories.present? %>
      <%= link_to "New", new_category_path, class: 'btn btn-danger btn-sm' %>
  <% end %>
  </div>

app/views/relatives/_categories_index.html.erb
<div>
  <%= form_tag relatives_path, method: :get do %>
  <ul class="category">
        <% @user.categories.each do |category| %>
          <% cache(category) do %>
            <li>
              <%= check_box_tag "filter[]", category.id, params[:filter] ? params[:filter].include?(category.id.to_s) : false, id: "cb#{category.id}", remote: true %>

              <label for="cb<%= category.id %>"><%= category.name %></label>

              <!-- <b class=''>(<%#= category.relatives.where(published: true).count %>)</b> -->
            </li>
          <% end %>
        <% end %>
      </ul>
      <%= submit_tag t('.find'), class: 'btn btn-success btn-category btn-sm' if @categories.present? %>
      <br>
      <%= link_to t('.new'), new_category_path, class: 'btn btn-category-2 btn-danger btn-sm' %>
  <% end %>
  </div>

app/views/relatives/_form.html.erb
<%= form_for @relative do |f| %>
  <%= render "shared/error_messages", object: @relative %>
  <div class="col-lg-6 center-block form_create">

    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :second_name %>
      <%= f.text_field :second_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :born %>
      <%= f.text_field :born, class: 'form-control', class: 'datepicker'  %>
    </div>

    <div class="form-group">
      <%= f.label :maiden_name %>
      <%= f.text_field :maiden_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :family_status %>
      <%= f.text_field :family_status, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :children %>
      <%= f.text_field :children, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.trix_editor :description, class: 'form-control-custom' %>
    </div>

    <div class="img-field">
      <%= f.label :images %>
      <%= f.file_field :images, multiple: true %>
    </div>

    <br>

    <div class="form-group">
      <%= link_to t(".show"), nil, class: 'button-show-categories btn btn-info', remote: true if @user.categories.present? %>
    </div>

    <div class="form-group category_group form-collaborators" id="relatives_category_id" >
      <%= collection_check_boxes(:relative, :category_ids, @user.categories, :id, :name) do |b| %>
      <%=  b.label(:"data-value" => b.value) { b.check_box + b.text } %>
      <% end %>
    </div>

    <div class="btn-form">
      <%= f.submit t('.submit'), class: 'btn btn-success btn_rel_new' %>
    </div>
  </div>

<% end %>

app/views/relatives/_images.html.erb
<div class="left">
<% if @relative.images.present? %>
  <% @relative.images.each do |picture| %>
    <%# cache(picture) do %>
      <% if @relative.images.first == picture %>
        <%= link_to image_tag(picture.url(:thumb)), asset_url(picture.url(:large)), data: { lightbox: "roadtrip" }, class: 'show_main_image' %>
        <br>
      <% else %>
        <%= link_to image_tag(picture.url(:small)), asset_url(picture.url(:large)), data: { lightbox: "roadtrip" }, class: "show_other_images" %>
      <% end %>
    <%# end %>
  <% end %>
<% end %>
</div>

app/views/relatives/_relative.html.erb
<% if relative.published %>
  <div class="product-card text-center products" style="width: 20rem">
    <div class="card-body">
      <% if relative.images.present? %>
        <%= link_to (image_tag relative.images[0].url(:small)), relative_path(relative) %>
      <% elsif %>
        <%= link_to (image_tag 'empty.png', width: 152), relative_path(relative) %>
      <% end %>
        <h2><%= link_to relative.first_name, relative_path(relative), class: 'Link_show_relative' %></h2>
        <% if relative.maiden_name.present? %>
          <h2><%= relative.second_name %>(<%= relative.maiden_name %>)</h2>
        <% else %>
          <h2><%= relative.second_name %></h2>
        <% end %>
      <h2><%#= sanitize relative.description.truncate(15) %></h2>
    </div>
      <%= link_to t('.delete'), relative, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' if current_user?(relative.user) %>
    <% if current_user?(relative.user) || relative.user.following?(current_user) %>
      <%= link_to t('.edit'), edit_relative_path(relative), class: 'btn btn-warning btn-sm' %>
    <% end %>
  </div>
<% end %>

app/views/relatives/edit.html.erb
<h2 class="text-center">Edit relative</h2>
<%= render 'form' %>

app/views/relatives/index.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-2">
      <% if @user.categories.present? %>
        <%= render 'categories_index', cache: true %>
      <% else %>
      <div class="categ_text">
        <span class=""><%= t('.no_categ') %></span>
      </div>
        <%= link_to t(".pedig_btn"), new_category_path, class: 'btn btn-danger btn-sm categ_btn' %>
      <% end %>
    </div>
    <div class="users_main col-md-10 row">
        <% if @user.relatives.present? %>
          <%= render @relatives, cache: true %>
        <% else %>
          <h2 class="col-10 text-center relat_text"><b><%= t('.text') %></b></h2>
        <% end %>
    </div>
  </div>
  <%= paginate @relatives, cache: true %>
<% else %>
  <%= render template: 'users/sessions/new' %>
<% end %>

app/views/relatives/new.html.erb
<% provide(:title, t(".new_relat")) %>
<%= render 'form' %>

app/views/relatives/show.html.erb
<% provide(:title, "#{@relative.first_name} #{@relative.second_name}") %>
<div class="show_relative">
    <%#= image_tag(@relative.image_url(:thumb), alt: 'Image') if @relative.image? %>
      <%= render 'images' %>
    <br>
    <% if @relative.maiden_name.present? %>
      <h2><%= @relative.first_name %> <%= @relative.second_name %>(<%= @relative.maiden_name %>)<h2>
    <% else %>
    <h2><%= @relative.first_name %> <%= @relative.second_name %></h2>
    <% end %>
  <!-- <br> -->
  <h4><%= @relative.born %></h2>
  <!-- <br> -->
  <h4><%= @relative.family_status %></h2>
  <!-- <br> -->
  <h4><%= @relative.children if @relative.children.present? %></h4>
  <div class="show_description">
    <h5><%= sanitize @relative.description %></h5>
  </div>
</div>