config/routes.rb
Rails.application.routes.draw do

  get 'emails/new'
  get 'emails/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  ActiveAdmin.routes(self)

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :admin_users, ActiveAdmin::Devise.config

    root 'relatives#index'

    get '/collaborators/new',      to: 'users#add_collaborator'
    get '/collaborators',      to: 'users#collaborators'

    resources :categories
    resources :authentications, only: [:destroy]
    resources :relationships,  only: [:create, :destroy]
    resources :emails,  only: :create
    resources :pages, only: :show
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :relatives do
      resources :categories
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <hr>
  <div class="container-fluid text-center">
    <div class="row">
      <div class="mr-auto">
      </div>

      <div class="mr-auto">
      </div>

      <div class="col-md-4">
        <% @pages.each do |page| %>
          <% cache(page) do %>
            <%== link_to page.title, page_path(page) %>
          <% end %>
        <% end %>
      </div>

      <div class="col-md-4">
        <% @socials.each do |social| %>
          <% cache(social) do %>
            <%= link_to social.body, target: "_blank" do %>
              <%= image_tag "#{social.image.mini.url}" if social.image.present? %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div class="float-right col-md-4">
        <%= image_tag 'tree_three.png', width: 100 %>
        <br>
        <span class="copyright"> Copyright &copy; <%= copyright_notice_year_range(2019) %> Family Tree - All rights reserved </span>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to (image_tag "tree.jpg", class: 'tree_img'), root_path %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <!-- <div class="col-md-9 row"> -->
          <% if logged_in? %>
            <%= link_to "All relatives", root_path, class: 'navbar_link'%>
            <%= link_to "New relative", new_relative_path(@user), class: 'navbar_link' %>
          </li>
            <%= form_tag relatives_path, method: :get, class: "form-inline my-2 my-lg-0 search_form" do %>
            <%= text_field_tag(
            :search,
            params[:search],
            placeholder: "Search",
            class: "form-control mr-sm-2", id: "search"
            ) %>
            <%= button_tag(type: "submit", class: "search") do %>
              <%= fa_icon "search lg" %>
            <% end %>
            <% end %>
      <!-- </div> -->
    </ul>

    <span class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= @user.name %>
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to "Profile", current_user, class: "dropdown-item" %>
        <hr>
        <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
        <hr>
        <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
      </div>
    </span>
    <%= link_to(image_tag(@user.image.mini.url, alt: "Img", class: "mini_image"), user_path(@user)) if @user.image.url.present? %>
    <% elsif signup_path %>
    <%= link_to "Log in", login_path, class: 'navbar_link' %>
    <% end %>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to (image_tag "tree_three.png", class: 'tree_img'), root_path %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!-- <li class="nav-item active"> -->
        <!-- <div class="col-md-9 row"> -->
          <% if user_signed_in? %>
            <%= link_to t('.all_rel'), root_path, class: 'navbar_link'%>
            <%= link_to t('.new_rel'), new_relative_path, class: 'navbar_link' %>
            <%= link_to t('.all_us'), users_path, class: 'navbar_link navbar-link-all-users'  %>
          <!-- </li> -->
            <%= form_tag users_path, method: :get, class: "form-inline my-4 my-lg-0 search_form" do %>
            <%= text_field_tag(
            :search,
            params[:search],
            placeholder: t('.search'),
            class: "form-control mr-sm-2", id: "search"
            ) %>
            <%= button_tag(type: "submit", class: "search") do %>
              <%= fa_icon "search lg" %>
            <% end %>
          <% end %>
            <!-- <li class="nav-item"> -->
              <!-- <div class='row'> -->
            </ul>
            <div class="row col-xs-4 ">

              <span class="<%= 'locale' if I18n.locale == :en %>"><%= link_to image_tag('ukr.jpg', width: 50), { locale: :ua }, class: 'nav-link' %></span>

              <span class="<%= 'locale' if I18n.locale == :ua %>"><%= link_to image_tag('usa.png', width: 50), { locale: :en }, class: 'nav-link' %></span>
              <!-- </div> -->
            <!-- </li> -->
      <!-- </div> -->

    <span class="nav-item dropdown">
      <a class="nav-link dropdown-toggle nav_name nav_name_2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class=''><%= current_user.name || "User" %></span>
      </a>
      <div class="dropdown-menu col-sm" aria-labelledby="dropdownMenuButton">
        <%= link_to t('.settings'), edit_user_registration_path, class: "dropdown-item nav_nav" %>
        <%= link_to t(".collabs"), collaborators_path, class: "dropdown-item" %>
        <hr>
        <%= link_to t('.logout'),  destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </span>

      <% if current_user.image.url.present? %>
        <%= link_to(image_tag(current_user.image.mini.url, width:50, alt: "Img", class: 'user-image-navbar'), edit_user_registration_path) %>
      <% else %>
        <%= link_to(image_tag('empty.png', width: 50, class: 'user-image-navbar'), edit_user_registration_path) %>
      <% end %>

    <% elsif %>
      <%= link_to t('.login'), user_session_path, class: 'navbar_link_1' %>
      <%= link_to t('.signup'), new_user_registration_path, class: 'navbar_link_2' %>

      <span class="<%= 'locale' if I18n.locale == :en %>"><%= link_to image_tag('ukr.jpg', width: 50), { locale: :ua }, class: 'img_locales' %></span>

      <span class="<%= 'locale' if I18n.locale == :ua %>"><%= link_to image_tag('usa.png', width: 50), { locale: :en }, class: 'img_locales_2' %></span>
    <% end %>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width,initial-scale=1.0, maximum-scale=1, user-scalable=no" />
  </head>

  <body>
    <div class="">
      <%= render 'layouts/navbar' %>

      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= "#{name}" %>">
          <a href="#" class="close" data-dismiss="alert" &#215;></a>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>


      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>